### ISSUE TITLE
An exception occurred when executed

### ISSUE THREAD

**Issue by geniusdomus28** [smealum/udsploit#15]
![20170622_214210](https://user-images.githubusercontent.com/29629290/27434652-6b07140e-5794-11e7-8536-f06457163744.jpg)

executing udsploit from homebrew menu make this screen appear.

did not happen when I was installing b9s (11.3.0) but it happens now.

homebrew launcher 2.0.0, system 11.4.0-33K, b9s 1.3, luma 8.0 

what could have gone wrong?

**Comment by ihaveamac** [comment]
udsploit doesn't work on 11.4. and why are you trying to run it when you already have luma?
